version: "3.9"

services:
  frontend:
    build:
      context: ./Frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL};

  public-frontend:
    build:
      context: ./Frontend/src
      dockerfile: Dockerfile  # your Nginx Dockerfile
    container_name: public-frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}

  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/app:/code/app
      - ./Backend/requirements.txt:/code/requirements.txt
      - ./Backend/etc/secrets:/etc/secrets/
    environment:
      - PYTHONUNBUFFERED=1
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - Admin_Email=${Admin_Email}
      - Admin_Password=${Admin_Password}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_Domain=${JWT_Domain}
    env_file:
      - .env